// Menu actions
export const OPEN_SIDEBAR_MENU = 'OPEN_SIDEBAR_MENU';
export const OPEN_LANGUAGE_MENU = 'OPEN_LANGUAGE_MENU';
export const CHANGE_ACTUAL_CONTENT = 'CHANGE_ACTUAL_CONTENT';
export const OPEN_HISTORY_MENU = 'OPEN_HISTORY_MENU';
// History actions
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
// File Manager actions
export const UPDATE_DUAL_EDITOR_FILE_BY_KEY = 'UPDATE_DUAL_EDITOR_FILE_BY_KEY';
export const UPDATE_DUAL_EDITOR_FILE_CONTENT_BY_KEY = 'UPDATE_DUAL_EDITOR_FILE_CONTENT_BY_KEY';

export const UPDATE_BULK_EDITOR_FILES = 'UPDATE_BULK_EDITOR_FILES';
